name: wireless_file_transfer
description: A Flutter app for wireless file transfer between laptop and Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  mobile_scanner: ^5.2.3
  bonsoir: ^6.0.1
  file_picker: ^8.1.7
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
